apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ismaildaoudi/devops-project-dsti-a22:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: task-pv-storage
          mountPath: /data
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim